CREATE TABLE EMP10
AS
SELECT *
FROM EMP;

SELECT *
FROM EMP;

--제약조건 추가하기
ALTER TABLE EMP10
ADD CONSTRAINT EMP10_EMPNO_PK PRIMARY KEY(EMPNO);
--  제약조건    제약조건 명      제약조건    컬럼명

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP10';

DESC EMP10;

CREATE TABLE DEPT10
AS
SELECT *
FROM DEPT;

SELECT *
FROM DEPT10;

ALTER TABLE DEPT10
ADD CONSTRAINT DEPT10_DEPTNO_PK PRIMARY KEY(DEPTNO);

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT10';

DESC DEPT10;

--외래키 추가
ALTER TABLE EMP10
ADD CONSTRAINT EMP10_DEPTNO_FK
FOREIGN KEY(DEPTNO) REFERENCES DEPT10(DEPTNO);
--          나의 컬럼           테이블명(부모테이블의 컬럼)

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP10';


--NOT NULL 제약조건 추가
ALTER TABLE DEPT10
MODIFY DNAME CONSTRAINT DEPT10_DNAME_NN NOT NULL;

DESC DEPT10;


--제약조건 조건 제거하기
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP05'; 

--기본키 삭제, 기본키는 특별하다 테이블마다 하나만 있으니까
ALTER TABLE EMP05
DROP PRIMARY KEY;

--테이블마다 여러개가 있는 제약조건은 제약조건명을 기입해서 없애야된다.
ALTER TABLE EMP05
DROP CONSTRAINT EMP05_JOB_UK;

ALTER TABLE EMP05
DROP CONSTRAINT EMP05_ENAME_NN;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP05';


--외래키 같은 제약조건들을 강제로 무시하고 객체들을 지우는 SQL문
DROP TABLE DEPT10 CASCADE CONSTRAINTS;

DROP TABLE EMP10;

