CREATE TABLE PURCHASE(
    CUSTOMER_NAME VARCHAR2(20),
    PRODUCT_NAME varchar2(50),
    QUANTITY number(6),
    PRICE NUMBER,
    CRE_DATE DATE
);

DESC PURCHASE;

SELECT *
FROM PURCHASE;

--INSERT INTO PURCHASE
--VALUE(CUSTOMER_NAME, PRODUCT_NAME
--, QUANTITY, PRICE , CRE_DATE)
--VALUES('AA', 'BB', 999999, 1, '99/01/01');
--
--INSERT INTO PURCHASE
--VALUE(CUSTOMER_NAME, PRODUCT_NAME
--, QUANTITY, PRICE , CRE_DATE)
--VALUES('AA', 'BB', 9999999, 1, '99/01/01');

--DROP TABLE PURCHASE;
