-- 파일명: 임찬우_studentDDL.sql
CREATE TABLE STUDENT(
    NO NUMBER(8) CONSTRAINT STUDENT_NO_PK PRIMARY KEY,
    ID VARCHAR2(30) CONSTRAINT STUDENT_ID_NN  NOT NULL,
    NAME VARCHAR2(30) CONSTRAINT STUDENT_NAME_NN NOT NULL,
    AGE NUMBER(3) CONSTRAINT STUDENT_AGE_NN NOT NULL,
    JOIN_DATE  DATE DEFAULT SYSDATE
);

DESC STUDENT;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'STUDENT';




