-- 임찬우

CREATE TABLE BAN(
    BAN_NO NUMBER CONSTRAINT BAN_BAN_NO_PK PRIMARY KEY,
    BAN_NAME VARCHAR2(100) NOT NULL,
    BAN_SIZE NUMBER(2) NOT NULL
);

CREATE TABLE STUDENT(
    STUDENT_NO NUMBER(2) CONSTRAINT STUDENT_STUDENT_NO_PK PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    BAN_NO NUMBER CONSTRAINT STUDENT_BAN_BAN_NO_FK REFERENCES BAN(BAN_NO)
);


SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'BAN';

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'STUDENT';

DESC BAN;
DESC STUDENT;

INSERT INTO BAN
VALUES (1, 'IT개발', 10);

SELECT *
FROM BAN;

INSERT INTO STUDENT
VALUES (1, '임찬우', 1);

SELECT *
FROM STUDENT;

SELECT B.BAN_NO, B.BAN_NAME, B.BAN_SIZE
    , S.STUDENT_NO, S.STUDENT_NAME
FROM BAN B INNER JOIN STUDENT S
ON B.BAN_NO = S.BAN_NO;